project:
  type: website
  output-dir: docs

website:
  title: "QEco 2025 --- Allesina lecture notes"
  sidebar:
    style: "docked"
    search: true
    contents:
          - index.qmd
          - lecture_1.qmd
          - lecture_2.qmd
  navbar:
    left:
      - href: index.qmd
        text: Lecture notes
      - about.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

